const pizzas = [
    "Margherita",
    "Marinara",
    "Prosciutto e funghi",
    "Quattro Stagioni",
    "Capricciosa",
    "Quattro Formaggi",
    "Diavola",
    "Chicken Breast",
    "BBQ Chicken",
    "Italian Tomato Pie",
    "Garlic Fingers",
    "Margherita (vegetarian)",
    "Marinara (vegan)",
    "Primavera (vegetarian)",
    "Bianca (vegetarian)",
    "Verdure Grigliate (vegetarian)",
    "Funghi (vegetarian)",
    "Caprese (vegetarian)",
    "Four Cheese (vegetarian)",
    "Roasted Vegetable (vegan)",
    "Mediterranean Veggie (vegan)",
    "Pepperoni",
    "Italian Sausage",
    "Meatball",
    "Hawaiian",
    "BLT",
    "BBQ Meat Lovers",
    "Philly Cheesesteak",
    "Bacon Cheeseburger",
    "Pepperoni and Sausage",
    "Chicken Alfredo",
    "Shrimp Scampi",
    "Cioppino",
    "Puttanesca",
    "Marinara (with clams)",
    "Frutti di Mare",
    "Lobster",
    "Seafood Medley",
    "Salmon",
    "Tuna Melt",
    "Buffalo Chicken",
    "BBQ Pulled Pork",
    "Mac & Cheese",
    "Barbecue Chicken Bacon Ranch",
    "Garlic Parmesan",
    "White Pizza (no sauce)",
    "Deep Dish",
    "Stuffed Crust",
    "Calzone",
    "Stromboli",
    "Neapolitan",
    "Sicilian",
    "Roman",
    "Chicago Deep Dish",
    "New York Style",
    "California Style",
    "Greek Pizza",
    "Turkish Pide",
    "Lahmacun",
    "Focaccia",
    "Margherita (Double Cheese)",
    "Marinara (Extra Garlic)",
    "Prosciutto e Funghi (Thin Crust)",
    "Quattro Stagioni (Spicy)",
    "Capricciosa (Loaded)",
    "Quattro Formaggi (White Sauce)",
    "Diavola (Extra Spicy)",
    "Chicken Breast (Buffalo Style)",
    "BBQ Chicken (Pineapple & Jalapeño)",
    "Italian Tomato Pie (Deep Dish)",
    "Garlic Fingers (Donair Sauce)",
    "Margherita (Extra Basil)",
    "Marinara (Extra Oregano)",
    "Primavera (Extra Veggies)",
    "Bianca (Extra Cheese)",
    "Verdure Grigliate (Extra Grilled Veggies)",
    "Funghi (Extra Mushrooms)",
    "Caprese (Extra Mozzarella)",
    "Four Cheese (Extra Cheese)",
    "Roasted Vegetable (Extra Veggies)",
    "Mediterranean Veggie (Extra Olives)",
    "Pepperoni (Extra Cheese)",
    "Italian Sausage (Extra Meat)",
    "Meatball (Extra Meat)"
];

module.exports = pizzas;
